### ISSUE TITLE
Error in python3 setup.py develop

### ISSUE THREAD

**Issue by willsmithorg** [Innixma/autogluon-benchmarking#6]
When I ran python3 on a default AMI instance I got:

```
running develop
/home/ec2-user/.local/lib/python3.7/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/home/ec2-user/.local/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/test-easy-install-9513.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.7/site-packages/

```

So far I've got a bit further with:
```
sudo python3 setup.py develop
```

**Comment by willsmithorg** [comment]
Hmm ... I'm guessing this repo is deprecated and superseded by Innixma/autogluon-benchmark, which has more recent updates.

**Comment by Innixma** [comment]
Apologies for this. I added a warning to the top of the readme indicating that this repo is likely not going to work without significant effort, and steps to run AutoMLBenchmark that are easier. Because of historical reasons, running AutoMLBenchmark was much more challenging when this repo was created than it is now, and required a lot of hacks.

We are publishing a JMLR paper in the next few months that is an updated version of our original paper. We plan to create an updated version of this repo at that time.

**Comment by willsmithorg** [comment]
Thanks for updating the README.
I'll have a go with AutoMLBenchmark.
